apiVersion: v1
kind: Service
metadata:
  name: foundation-project-service
spec:
  selector:
    app: foundation-project
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foundation-project
  labels:
    app: foundation-project
spec:
  selector:
    matchLabels:
      app: foundation-project
  template:
    metadata:
      labels:
        app: foundation-project
    spec:
      containers:
      - name: foundation-project
        image: vlin303/foundation-project:latest
        ports:
        - containerPort: 5000
