apiVersion: v1
kind: Service
metadata:
  name: ppclass-gen-service
spec:
  selector:
    app: ppclass-gen
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ppclass-gen
  labels:
    app: ppclass-gen
spec:
  selector:
    matchLabels:
      app: ppclass-gen
  template:
    metadata:
      labels:
        app: ppclass-gen
    spec:
      containers:
      - name: ppclass-gen
        image: vlin303/classgenimage:latest
        ports:
        - containerPort: 5001
