apiVersion: v1
kind: Service
metadata:
  name: ppfront-end-service
spec:
  selector:
    app: ppfront-end
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ppfront-end
  labels:
    app: ppfront-end
spec:
  selector:
    matchLabels:
      app: ppfront-end
  template:
    metadata:
      labels:
        app: ppfront-end
    spec:
      containers:
      - name: ppfront-end
        image: vlin303/frontendimage:latest
        ports:
        - containerPort: 5000
