apiVersion: v1
kind: Service
metadata:
  name: pphealth-gen-service
spec:
  selector:
    app: pphealth-gen
  ports:
  - protocol: TCP
    port: 5003
    targetPort: 5003
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pphealth-gen
  labels:
    app: pphealth-gen
spec:
  selector:
    matchLabels:
      app: pphealth-gen
  template:
    metadata:
      labels:
        app: pphealth-gen
    spec:
      containers:
      - name: pphealth-gen
        image: vlin303/healthgenimage:latest
        ports:
        - containerPort: 5003
