apiVersion: v1
kind: Service
metadata:
  name: ppname-gen-service
spec:
  selector:
    app: ppname-gen
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 5002
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ppname-gen
  labels:
    app: ppname-gen
spec:
  selector:
    matchLabels:
      app: ppname-gen
  template:
    metadata:
      labels:
        app: ppname-gen
    spec:
      containers:
      - name: ppname-gen
        image: vlin303/namegenimage:latest
        ports:
        - containerPort: 5002
